"""
This type stub file was generated by pyright.
"""

from . import version
from .ticker import Ticker
from .tickers import Tickers
from .multi import download

__version__ = ...
__author__ = ...
def pdr_override(): # -> None:
    """
    make pandas datareader optional
    otherwise can be called via fix_yahoo_finance.download(...)
    """
    ...

