"""
This type stub file was generated by pyright.
"""

user_agent_headers = ...
def empty_df(index=...):
    ...

def get_html(url, proxy=..., session=...): # -> str:
    ...

def get_json(url, proxy=..., session=...): # -> Any | dict[Unknown, Unknown]:
    ...

def camel2title(o): # -> list[str]:
    ...

def auto_adjust(data):
    ...

def back_adjust(data):
    """ back-adjusted data to mimic true historical prices """
    ...

def parse_quotes(data, tz=...):
    ...

def parse_actions(data, tz=...): # -> tuple[Unknown, Unknown]:
    ...

class ProgressBar:
    def __init__(self, iterations, text=...) -> None:
        ...
    
    def completed(self): # -> None:
        ...
    
    def animate(self, iteration=...): # -> None:
        ...
    
    def update_iteration(self, val=...): # -> None:
        ...
    
    def __str__(self) -> str:
        ...
    


